### ISSUE TITLE
Deprecated dependencies in @vercel/nft: npmlog and are-we-there-yet

### ISSUE THREAD

**Issue by Johnwjl** [vercel/nft#440] opened 2024-09-09 14:00 UTC
- Operating System (or Browser): macOS
- Node Version: 20.17.0
- Link to reproduction: https://stackblitz.com/edit/nuxt-starter-m7qsfv?file=README.md 

### Description

I'm using `nuxt@3.13.1` which depends on `nitropack@2.9.7`, and I noticed that it introduces some deprecated subdependencies:

- `npmlog@5.0.1`
- `are-we-there-yet@2.0.0`

These deprecated packages are coming from `@mapbox/node-pre-gyp@1.0.11`, which is a dependency of `@vercel/nft@0.26.5`. Could you please consider updating `@mapbox/node-pre-gyp` or addressing these deprecated dependencies?

### Steps to reproduce

1. Install `nuxt@3.13.1`
2. Run `pnpm install`
3. Observe the deprecation warnings related to the above dependencies.

Could you please consider updating `npmlog` `rimraf` and addressing these deprecated dependencies?

### Steps to reproduce

1. Install a project that depends on `@mapbox/node-pre-gyp`
2. Run `pnpm install`
3. Observe deprecation warnings about these packages.

Dependency chain:
```sh
nuxt 3.13.1
└─┬ nitropack 2.9.7
  └─┬ @vercel/nft 0.26.5
    └─┬ @mapbox/node-pre-gyp 1.0.11
      └─┬ npmlog 5.0.1
        └── are-we-there-yet 2.0.0
        └── gauge 3.0.2
      └── rimraf 3.0.2
         └── glob 7.2.3
```

**Comment by anviksuteiriy** [comment] 2024-09-12 04:01
1+ for this request

**Comment by styfle** [comment] 2024-09-13 18:53
Closing as a duplicate of #421

**Closed by styfle** 2024-09-13 18:53 UTC
